services:
  litellm:
    image: ghcr.io/ninthless/llm-gateway-lite:latest
    pull_policy: always
    environment:
      DATABASE_URL: postgresql://litellm:replace-with-random-postgres-password@${rca_svc_db_postgres}/litellm
      LITELLM_MASTER_KEY: sk-replace-with-random-master-key
      LITELLM_SALT_KEY: sk-replace-with-random-salt-key
      STORE_MODEL_IN_DB: "True"
      NO_DOCS: "True"
      NO_REDOC: "True"
      NO_OPENAPI: "True"
    ports:
      - "4000:4000"

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: litellm
      POSTGRES_USER: litellm
      POSTGRES_PASSWORD: replace-with-random-postgres-password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"

volumes:
  postgres_data:
